export const USER_API = 'https://api.lookmanhua.com/';   
export const IMGBASE_API = 'http://static.lookmanhua.com/img?s=';
export const HOME = USER_API + 'app/index';//首页
export const SEARCH_KEY_API = USER_API + 'Comic/keysearch'; //热门搜索api
export const CATEGORY_TICAI_API = USER_API + 'comic/topic'; //题材分类api
export const CONTENT_CONTENT_API = USER_API + 'comic/classify'; //内容分类api
export const CARTOON_INFO_API = USER_API + 'comic/detail'; //漫画信息
export const CARTOON_CHAPTERS_API = USER_API + 'comic/comicpart'; //漫画章节
export const CHAPTER_DETAIL_API = USER_API + 'comic/detailpart'; //漫画章节详情
export const GETWEEKDAY = USER_API + "comic/week"; //获取指定周几的漫画列表
export const GETHOTREVIEW = USER_API+"comic/hotreview";//获得热门榜
export const OVERCARTOON = USER_API+"comic/overspv"; //完结榜
export const NEWCARTOON = USER_API+"comic/newforweek";//新品榜
export const GETHOTCARTOON = USER_API+"comic/red"; //获取最热漫画
export const GETNEWCARTOON = USER_API+"comic/newcomic"; //获取最新漫画
export const GETFINISHCARTOON = USER_API+"comic/overs"; //获取完结的漫画
export const SEARCHBYKEY_API = USER_API + "comic/search"; //获取完结的漫画
export const GETTOPIC = USER_API+"comic/topic"; //获取题材列表
export const GETOPICCOMIC = USER_API +"comic/topiccomic";//获取题材下的漫画列表
export const FROM = '2'
